session.go
session_test.go

A interface has two elements, a type and a value. A interface value is
only nil if both elements are nil. However if we return `AccepStream()`
directly, net.Conn will be: `(net.Conn, nil)`. Even if the inner value is
nil, this value will be non-nil. So when `Open()` and `Accept()` return an
error, the value (in our example net.Conn) will be always non-nil.
This commit fixes it by explicit returning a nil. More detail about
this can be found: http://golang.org/doc/faq#nil_error

session: return explicit nil to avoid non-nil interface value

---

const.go
mux.go
session.go
session_test.go

If you take out the timeout, the unit test will deadlock when the `Read()` call tries to send the window update. I'm not sure I like the special-case body check in here but I thought I'd push it up so you can take a look (if there's a body we already have an optional deadline interface outside of here).

Fixes read/write loop and ping deadlocks

---

const.go
mux.go
session.go
session_test.go

This opens up the timeout to the user's payloads as well as just control headers. It's a little indirect because we don't have a timeout in the `send()` goroutine directly, but this timeout effectively covers that because the caller is waiting for that goroutine to put the write error onto the error feedback channel.

Generalizes the header write timeout to a broader "safety valve" write timeout.

---

const.go
session.go
session_test.go

This adds a timeout of `ConnectionWriteTimeout` for pings. If a keepalive fails, the connection is closed.
Modify test code to turn off keepalives on tests that want to fail for other reasons (since keepalive will tend to fail them faster than the situation under test).

Fixes #12 KeepAlive is not working

---

session_test.go
stream.go

This PR adds the `Shrink` method that allows the receive buffers of a Stream to be truncated to zero. This can be useful when connection pooling may keep idle Streams around, as they may have grown their internal buffers to be fairly large (256KB max by default).
/cc: @slackpad

Support shrinking of receive buffers of a stream

---

session.go
session_test.go
stream.go

This takes #28 which fixes #26 but puts all the logic on the side opening the stream, so we don't depend on any updated logic or messages from the other side. In addition:
* Modified the logic to clean up the `synCh` when a stream is established (like before) and any time a stream is closed. This latter change is easier to reason about, and we don't have to trace through every possible close scenario to make sure we catch them all.
* Changed the `panic()`s in the `synCh` handling code to `ERR` logs, since underflowing that channel _could_ happen from a misbehaving client on the other side sending extra ACKs. Also, this is recoverable, so we don't need to panic.
* Added some cleanup code for `synCh` if the initial window update can't be sent.

Properly handles closing streams before they are ACKed.

---

session_test.go
stream.go

Should address bug #26. The issue occurs when opening unidirectional streams then closing them quickly before the other side can ACK the open.

properly handle closing streams before they are ACKed

---

stream.go

Calling time.After creates a runtime timer that gets scheduled into the runtime. Doing this frequently will bog the scheduler down and have weird effects on the program. Using a timer instead will let us stop the timer and free up those resources when we exit the function

use a timer instead of 'After' to avoid leaking resources

---

stream.go

This is a race condition found running my own code with `-race`. Running the tests for this library with `-race` results in many, what I think are probably not important, race conditions and fails some tests. So writing a test case for this is impossible with the current state of the tests.
From what I can see no other place tries to lock `recvLock` and `stateLock` at the same time so this shouldn't introduce any deadlocks.

Fix race for recvBuf

---

session.go
session_test.go
stream.go

I commonly use the following style to wait until a connection closes to handle further cleanup...
```go
go func() {
<-session.CloseChan()
// Do some cleanup, close other parent connections...
}()
```
Would be great to see this feature upstream.

Add public session CloseChan method

---

stream.go

I found this race condition when running my code using yamux with `-race`. 
Since the test suite fails when run with `-race` I don't think I can write a meaningful test here.

Fix race around read and write deadlines in Stream

---

bench_test.go
session.go
session_test.go
stream.go
util.go

Streaming perf improv

---

session.go

The keepalive runs in its own go routine and its likely the session gets closed out from under it. In this case we should not output an error but rather should handle it like the next case in the select below which is to just return.

Dont output keepalive error when the session is closed

---

bench_test.go

Refactor benches and add finer grained bench cases:
1. Minor cleanups (inconsistent var names between similar code, etc)
2. Report allocs and throughput
3. Run benches with fixed parameters with a wider array of inputs to better show scaling effects
4. Implement parallel version of primary bench test
Example output:
```
BenchmarkPing-16                    	  200000	      7719 ns/op	     458 B/op	       8 allocs/op
BenchmarkAccept-16                  	  100000	     21225 ns/op	    1412 B/op	      22 allocs/op
BenchmarkSendRecv32-16              	  200000	      6279 ns/op	   5.10 MB/s	      80 B/op	       2 allocs/op
BenchmarkSendRecv64-16              	  200000	      6380 ns/op	  10.03 MB/s	      80 B/op	       2 allocs/op
BenchmarkSendRecv128-16             	  200000	      6192 ns/op …
```

Improve yamux benches

---

session_test.go
stream.go

This change causes new deadlines to impact currently blocked reads and
writes. This is inline with the documentation of deadlines on a
[net.Conn](https://golang.org/pkg/net/#Conn).
This PR can close #https://github.com/hashicorp/yamux/pull/51

Deadline updates impact blocked reads and writes

---

go.mod
mux.go
session_test.go
stream.go

This adds a new setting StreamCloseTimeout which forcibly closes the
connection if the remote side doesn't ACK a FIN within the given
timeout. This should only happen in cases the remote side is buggy and
doesn't call `Close` properly.
This allows the Session to release the mapping to the stream and
therefore avoids a memory leak when one side of a stream never completes
a close.
"Forcibly close" in this case means: (1) send a RST (2) delete the
receive buffer (3) delete the stream. Future packets received for the
stream will be dropped (and a log message produced).

add StreamCloseTimeout

---

const.go
session_test.go

Fix #90 
Golang standard http server package will read from connections in background to detect if it's alive. It set read deadline on connection and detect if the returned error is timeout error which implements net.Error.
If not, it will call `cr.handleReadError(err)` and then call `cr.conn.cancelCtx()`, so server `request.Context()` will be canceled too.
```go
func (cr *connReader) backgroundRead() {
n, err := cr.conn.rwc.Read(cr.byteBuf[:])
cr.lock()
if n == 1 {
cr.hasByte = true
// We were past the end of the previous request's body already
// (since we wouldn't be in a background read otherwise), so
// this is a pipelined HTTP request. Prior to Go 1.11 we used to
// send on the CloseNotify channel and cancel the context here,
// but the behavior was documented as only "may", and we …
```

let ErrTimeout implements net.Error

---

stream.go

This commit takes a minimal approach to fixing unsafe header re-use during close and timeout by reallocating the header in those cases.
Fixes #40
Related #102

Fix unsafe header re-use on close and timeout

---

session.go

We now create a new header slice instead of taking a `sendLock` as this is a rare occurance.
This should fix some rare race conditions with simultaneous reads/writes to `sendHdr`.
I believe I've identified another potential race condition in `(*Session).waitForSendErr` which might warrant further investigation:
1. `(*Stream).write` calls `(*Session).waitForSendErr`, passing `s.sendHdr` (whilst locked)
2. `(*Session).waitForSendErr` passes `s.sendHdr` on to `(*Session).send` via `s.sendCh` (which is buffered)
3. Send times out (or server shuts down), `waitForSendErr` returns, `write` exists and leaves `s.sendHdr` unprotected

Fix use of unprotected `stream.sendHdr` in session

---

session.go

This removes a for loop around io.Writer.Write() calls in
session.send(). The loop looks like what you would write in C when
making write(2) syscalls. With C and write(2), you need to account for
partial writes and call write(2) more than once. This is not how Go's
io.Writer works. The io.Writer contract clearly states that "Write
must return a non-nil error if it returns n < len(p)". Dealing with
partial writes is the responsibility of _implementations_ of
io.Writer, not that of callers.
Removing the for loop makes the code simpler and more idiomatic.

Remove unnecessary for loop in Session.send()

---

session_test.go

fixing failing test in go 1.12 :
see https://github.com/hashicorp/yamux/issues/71
```
19:15:03/Users/pierrot/dev/yamuxλ go test --count=1 ./...
2019/05/12 19:15:16 [ERR] yamux: keepalive failed: i/o deadline reached
--- FAIL: TestSendData_Large (0.40s)
session_test.go:427: err: session shutdown
session_test.go:396: err: EOF
2019/05/12 19:15:16 [WARN] yamux: failed to send ping reply: session shutdown
2019/05/12 19:15:24 [WARN] yamux: failed to send ping reply: connection write timeout
FAIL
FAIL	github.com/hashicorp/yamux	9.505s
19:15:25/Users/pierrot/dev/yamuxλ git checkout -
M	go.mod
Switched to branch 'fix_test'
Your branch is up-to-date with 'pmalhaire/fix_test'.
19:15:56/Users/pierrot/dev/yamuxλ go test --count=1 ./...
ok  	github.com/hashicorp/yamux	9.911s
```

fix failing test

---

stream.go

This allows properly recording partial reads on connection break
Partially addresses #94

Record actual copied length

---

session_test.go
stream.go

If the sending side of a stream closes both their stream and their
session, a partial read of the final frame on the receiving side may
fail because the receiving side tries to send a window update on a
closed session.
This commit changes Stream.Read() so that it ignores "session
shutdown" errors return by Stream.sendWindowUpdate(). This will let
Read() calls consume all of the final frame.

Fix failing partial read on last frame of closed session

---

mux.go
session.go
util.go

*log.Logger is not a good choice as a parameter.

Fix hashicorp/yamux#72, abstract logger into interface

---

.github/workflows/test.yaml
bench_test.go
go.mod
mux.go
session.go
session_test.go
stream.go

It now passes:
- `golangci-lint run ./...`
- `go test -race ./... -short`
The `-short` is needed because both of `TestSendData_VeryLarge` and `TestSendData_Large` fail for timing reasons (since race mode is generally slower) and I was hesitant to rewrite them to be less timing sensitive, so I have them get skipped when in testing short mode for now.

chore: update tests to pass the race detector and linter

---

stream.go

Concurrent operations on the stream are "safe" inasmuch as they don't cause a data race. That is, calling close concurrently with a read won't panic, you can write and read concurrently, and reading from two different goroutines shouldn't result in short reads. But there's no intended guarantee that the reads are semantically meaningful if you're reading concurrently.
Fixes: https://github.com/hashicorp/yamux/issues/128
Fixes: https://hashicorp.atlassian.net/browse/NET-10293

docs: clarify the semantics of concurrent `Read` calls

---

stream.go

In #136 we documented warnings around the semantics of calling `Stream.Read` concurrently. But we assumed without investigating that the concurrent operations were actually safe. But in fact the locks made by multiple Read calls can interleave, causing a deadlock. Update the documentation again to make this clear.
Fixes: https://github.com/hashicorp/yamux/issues/139

docs: stream Reads are not safe for concurrent use
